version: '3'
services:
  streamer:
    build: ./streamer
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - db
    env_file:
      - docker/env/.streamer.env

  enrichments_processor:
    build: ./enrichments_processor
    restart: always
    ports:
      - 8086:8085
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - db
    env_file:
      - docker/env/.enrichments_processor.env

  watchdog:
    build:
      context: ./streamer
      dockerfile: ./Dockerfile.watchdog
    restart: always
    ports:
      - 8087:8080
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - db
    env_file:
      - docker/env/.streamer.env

  db:
    build: './db'
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - connect
      - ksqldb-server
    env_file:
      - docker/env/.postgres.env
